jquery/jquery-ui

tests/unit/datepicker/datepicker_options.js
If you would rather mock the current date so this doesn't happen again (or use the current date - 2008 to work out the offset) then I can refactor
=> Fix DatePicker Tests running in 2015

Gruntfile.js, tests/unit/calendar/calendar_core.js, tests/unit/calendar/calendar_test_helpers.js, tests/unit/datepicker/datepicker_events.js
* Make keyboard tests work in phantom 
* Run datepicker tests in Grunt qunit task
Remaining: spinner tests (due to Globalize update?)
=> Calendar: Fix unit tests for CMD

tests/unit/autocomplete/autocomplete_core.js, tests/unit/autocomplete/autocomplete_options.js, tests/unit/menu/menu_events.js, tests/unit/selectmenu/selectmenu_core.js, ui/menu.js, ui/selectmenu.js
So far we were using ui-state-active on active parent items, ui-state-focus on active child items. The theme update highlighted the visual inconsistency. With this change, only ui-state-active is used.
Fixes [#10692](http://bugs.jqueryui.com/ticket/10692)
This also affects autocomplete and selectmenu, since they both use menu. Only selectmenu tries to mess with menu classes.
The `theme.css` change needs to be dropped and is there only to show what the menu will look like after #1384 lands. As long as we land both before 1.12, this can also land before #1384.
Tested using browserstack-runner locally, running all three affected testsuites, along with clicking around demos and visual tests manually in Chrome.
=> Menu: Use ui-state-active consistently

themes/base/dialog.css
The `background-position: 16px 16px;` on the SE handle doesn't seem to be necessary now that the handle is small so I removed it.
I tested this on a few browsers on my Mac and some Windows VMs and it looks to be good. I still think these targets are too small, but by design this PR keeps the status quo.
=> Dialog: Remove overflow: hidden and reposition resize handles

tests/unit/progressbar/progressbar_core.js, tests/unit/progressbar/progressbar_events.js, tests/unit/progressbar/progressbar_methods.js, tests/unit/progressbar/progressbar_options.js, tests/unit/widget/widget_extend.js
Noticed these while working on other style fixes. Esformatter won't address these, so might as well fix them now.
=> Fix missing wrappers

Gruntfile.js, package.json
Also formats `jscsBad` array and sorts it alphabetically.
=> Build: Increase htmllint coverage by testing all files, ignoring errors

ui/tabs.js
Powered by esformatter! Will do more of these with individual files.
=> Tabs: Fix style issues

tests/unit/effects/core.js, ui/effect.js
Adds two clunky tests to at least check that no exception is thrown.
Fixes #12223
=> Effect: Make .transfer() callback optional

external/date.js, tests/unit/calendar/calendar_options.js, ui/calendar.js
This PR addresses @jzaefferer bug reports regarding the use of multiple-month and other-months demo / option. Some other related issues (with keyboard control) should be fixed now, too. See Datepicker Wiki (ToDo section).
> * demos/calendar/multiple-months.html: Clicking a date on the second or third month changes the display to show that month as the first month. Only clicking the next/prev buttons should change that.
> * demos/calendar/other-months.html: Very similar problem as the previous one, clicking lead days changes the month
https://github.com/jquery/jquery-ui/pull/1316#issuecomment-56192690
This PR introduces a couple of changes. Mainly removing the selected property from $.date and splitting the $.date object for ongoing modifications of the current value and the $.date object …
=> Calendar: fix month jumping WIP

tests/unit/spinner/common-deprecated.js, tests/unit/spinner/deprecated.html, tests/unit/spinner/deprecated.js, ui/spinner.js
This pr moves the `_uiSpinnerHtml` and `_buttonHtml` extension points into backcompat
=> Spinner html

ui/autocomplete.js
This is a call on the menu widget, not using an event alias.
Ref 8b4ce807cd97e3cb953995934d6c4f614de9fa03
Ref #12770
After staring at the surrounding code for a while, I figured that its not worth the effort to try and add a unit test.
Replaces gh-1566
=> Autocomplete: Revert mistaken event alias change

demos/draggable/handle.html, demos/draggable/sortable.html, demos/sortable/connect-lists.html, demos/sortable/default.html, demos/sortable/display-grid.html, demos/sortable/empty-lists.html, demos/sortable/items.html, demos/sortable/placeholder.html, demos/widget/default.html
Noticed this while looking at demos for gh-1599.
=> Demos: Deal with missing disable-selection dependency

package.json
Fixes #14375
Very simple change that probably needs a lot of explanation. To show that this actually works, I've created a proper demo: https://github.com/jzaefferer/webpack-jquery-ui
That was inspired by this demo, which contained a lot of unrelated things: https://github.com/bebraw/jquery-ui-webpack-demo
Which in turn was using this `index.js` (default when `"main"` property isn't specified): https://github.com/bebraw/jquery-ui/commit/9574b6ede7287a39741410363745f625fabc1b01
It turned out that using an index file with a list of all components, besides the annoying maintenance, is also bad for webpack builds, since it ends up including *everything* listed in that file. On the other hand, including specific components, like in my demo, only includes that component and its dependencies. …
=> Build: Add main entry for webpack support; actual value doesn't matter

build/release.js
Fixes [#11101](http://bugs.jqueryui.com/ticket/11101)
Both me and Scott now are owners of the `jquery-ui` npm package. Devon is still an owner, too, we can remove him later.
=> Release: Publish to npm

tests/unit/draggable/core.js, ui/widgets/draggable.js, ui/widgets/mouse.js
=> Mouse: Don't stop propagation of mouseup

ui/core.js, ui/jquery-1-7.js, ui/position.js, ui/widget.js, ui/widgets/accordion.js, ui/widgets/autocomplete.js, ui/widgets/button.js, ui/widgets/checkboxradio.js, ui/widgets/controlgroup.js, ui/widgets/datepicker.js, ui/widgets/dialog.js, ui/widgets/draggable.js, ui/widgets/menu.js, ui/widgets/mouse.js, ui/widgets/progressbar.js, ui/widgets/resizable.js, ui/widgets/selectable.js, ui/widgets/selectmenu.js, ui/widgets/slider.js, ui/widgets/sortable.js, ui/widgets/spinner.js, ui/widgets/tabs.js, ui/widgets/tooltip.js
Collapses "UI Core" and "Core" into just "Core".
Fixes bad paths for CSS dependencies. Regressed when moving widgets into the widgets subfolder.
=> All: Fix manifest issues for categories and CSS dependencies

tests/unit/draggable/draggable.html, tests/unit/draggable/options.js
These failed when running through tests/unit/all.html, due to the smaller
iframe. Reducing a browser window enough triggered the same issue. Making
the top offset much smaller fixes that.
The rest is fixing bad indent and adds a missing module call.
I ran tests through browserstack-runner locally, on these, everything passes:
```
"chrome_current",
"firefox_current",
"opera_current",
"safari_current",
"ie_8",
"ie_9",
"ie_10",
"ie_11",
"edge_latest"
```
=> Draggable: Fix options tests

tests/unit/dialog/options.js, tests/unit/selectmenu/core.js, tests/unit/selectmenu/methods.js
IE8 still doesn't keep the space in the text (or HTML) representation. We don't really care, so adding more trims in these tests as well.
Fixes both of these: http://swarm.jquery.org/job/1478
Tested with BrowserStack on IE8.
=> Tests: Fix button space assertions on IE8

tests/unit/controlgroup/controlgroup.html, tests/unit/controlgroup/core.js, ui/widgets/controlgroup.js
Creating the label broke while doing a refactoring, the lack of tests allowed that to go unnoticed. Shouldn't happen again with the extra tests, covering both controlgroupLabel and spinner.
=> Controlgroup: Fix create and destroy for controlgroupLabel

ui/effects/effect-transfer.js
Download builder replaces return statements while concatenating a bundle, but fails to deal with this nested return. Since this module is already deprecated, pulling the return to the top level makes more sense.
=> Effects: Refactor transfer back compat to avoid bad nested return

tests/unit/calendar/core.js, tests/unit/date/core.js, tests/unit/datepicker/core.js, themes/base/calendar.css, ui/widgets/calendar.js, ui/widgets/datepicker.js
* Calendar: Fix tab index for prev / next buttons
* Calendar: Fix ARIA / id attributes for multiple grids
* Datepicker: Fix focus after date selection and after leaving the widget by using tab
* Calendar: Do not rebuilt whole calendar when a date is selected (improves performance, fixes datepicker issues)
This should fix all "Focus related" issues in the wiki: http://wiki.jqueryui.com/w/page/12137778/Datepicker
See section "6 - Open issues being discussed" -> "Next Steps / ToDo"
=> Calendar / Datepicker: a11y (fixes focus and tab index handling)

tests/unit/menu/core.js, ui/widgets/menu.js
This issue was introduced by 0bbd1569182bc03e8dc4f5f8aa203e8edbe15f99, which reduced the use of ui-state-focus and ui-state-active to using only ui-state-focus. This introduced the issue addressed here.
The fix is more of a workaround. With test test in place, we can investigate a better solution in the future.
Fixes [#14919](https://bugs.jqueryui.com/ticket/14919)
=> Menu: Remove active class from top-level item when menu is blurred

bower.json, package.json, tests/unit/calendar/common.js, tests/unit/datepicker/common.js, tests/unit/datepicker/core.js, ui/widgets/calendar.js, ui/widgets/datepicker.js
This PR adds some missing a11y functionality to match the specs in wiki and updates the globalize / cldr dependencies.
Besides, I started implementing the classes option using `this._addClass` and `this._removeClass` methods. This required to change the HTML rendering from string concatenation to jQuery elements. For now I changed this for all elements except for the day rendering. For elements created once or a few times this should be no problem at all (header, header buttons, table header, etc.), but the day elements are rendered quite often so this could have some performance impact. 
Please give me some feedback on how to handle day elements and how to improve the classes implementation in general.
=> Calendar / Datepicker: a11y improvements, classes and icons options

tests/unit/calendar/core.js, tests/unit/calendar/helper.js, tests/unit/calendar/methods.js, tests/unit/calendar/options.js, tests/unit/datepicker/core.js, tests/unit/datepicker/methods.js, tests/unit/datepicker/options.js
Extract all `new Date()` occurrences in order to simplify a possible fix for our unit test timezone issue.
=> Calendar: Create helper methods for Date object creation

ui/effect.js, ui/widgets/datepicker.js
https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryexprfilters-is-deprecated-use-jqueryexprpseudos
=> Use `expr.pseudos` instead of deprecated `expr.filters`

ui/i18n/datepicker-da.js
The term for "Today" in Danish is "I dag" not "Idag". This is a common misspelling in the Danish language. 
see https://dsn.dk/?retskriv=idag 
Dansk Sprognævn (DSN) is the authority over the Danish language.
=> Datepicker: Fix typo in currentText in da localization

demos/sortable/default.html
.disableSelection() was deprecated in v1.9, I thought it should be removed from the demos default page.
http://api.jqueryui.com/disableSelection/
=> remove reference to .disableSelection() from demos

demos/position/cycler.html, tests/lib/bootstrap.js, tests/unit/accordion/common.js, tests/unit/accordion/core.js, tests/unit/accordion/options.js, tests/unit/datepicker/core.js, tests/unit/datepicker/options.js, tests/unit/dialog/core.js, tests/unit/menu/core.js, tests/unit/menu/events.js, tests/unit/menu/helper.js, tests/unit/menu/methods.js, tests/unit/sortable/core.js, tests/unit/sortable/events.js, tests/unit/sortable/options.js, tests/unit/spinner/options.js, tests/visual/compound/draggable_resizable.html, tests/visual/effects/effects.js, tests/visual/selectmenu/selectmenu.html, ui/jquery-1-7.js, ui/widgets/accordion.js, ui/widgets/datepicker.js, ui/widgets/dialog.js
jQuery positional selectors () have been [deprecated in jQuery 3.4.0](https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/) and they'll be removed in jQuery 4.0.0. This PR removes their usage.
Most of the changes were possible without changing public API. However, dropping `:even` usage required a change to the [`header` option of the accordion widget](https://api.jqueryui.com/accordion/#option-header). I made it an optional function; any other suggestions?
=> All: Remove usage of jQuery positional selectors

tests/unit/datepicker/methods.js, ui/widgets/datepicker.js
Ticket: [15250](https://bugs.jqueryui.com/ticket/15270)
=> datepicker: memory leak

ui/i18n/datepicker-hu.js
Apply Hungarian language rules on datepicker Hungarian translation.
=> Datepicker: Fix Hungarian localization to use uppercase for first characters

tests/lib/bootstrap.js
This is necessary to catch all possible warnings that the test files may
trigger.
=> Tests: Load jQuery Migrate before UI test files

demos/tabs/sortable.html, tests/unit/button/core.js, tests/unit/checkboxradio/core.js, tests/unit/checkboxradio/events.js, tests/unit/menu/core.js, ui/effects/effect-size.js, ui/widgets/button.js, ui/widgets/selectmenu.js, ui/widgets/tooltip.js
This also adds a new internal `$.ui.__safeOffset__` method to provide a similar support to past jQuery versions while avoiding Migrate warnings.
=> All: Resolve most jQuery Migrate warnings

tests/unit/effects/core.js
jQueries older than 1.11 or 2.1 were leaving a timer in the queue which could
then influence other tests.
=> Tests: Clear the timers queue in an animateClass test

tests/unit/position/core.js
jQuery 3.2 incorrectly handle scrollbars in WebKit/Blink-based browsers.
This is fixed in version 3.3, see https://github.com/jquery/jquery/issues/3589.
As the data here comes from jQuery directly and the changes to fix it
are non-trivial: https://github.com/jquery/jquery/pull/3656, just accept
that scrollbar data in this jQuery version is inaccurate.
Ref jquery/jquery#3589
Ref jquery/jquery#3656
=> Tests: Skip a scrollbar test in jQuery 3.2

tests/unit/effects/core.js
jQuery 3.2 & newer have a different animation logic and the animated elements
width/height differ from the starting ones even at the beginning of the
animation. The point of the assertions checking that they're identical was
to ensure bug #5245 is fixed; that issue manifested by a big jump to half the
element size. To test for that, it's enough to check that the first obtained
values are close to the original ones.
This makes effects tests pass in all supported jQuery versions.
Ref #5245
=> Tests: Accept a small difference of animated width/height

tests/lib/qunit-assert-domequal.js
jQuery >=3.4.0 uses a special focus/blur handler pair
needed to fix various issues with checkboxes/radio buttons
as well as being able to pass data in focus triggers.
However, this leaves dummy focus & blur events if any of these
events were ever listened to at a particular element. There's not
a lot UI can do to fix this so we now just skip these handlers for
data comparisons in tests.
Ref jquery/jquery#4496
=> Tests: Account for extra focus/blur listeners in jQuery >=3.4

ui/widgets/menu.js
jQuery >=3.2 doesn't include scrollbars in `.height()`, this commit switches
it to `.innerHeight()` which does so in jQuery >=3.3. In  jQuery 3.2 it doesn't
either so include scrollbars in innerHeight, add it back.
Using `.innerHeight()` instead of `.height()` should be fine as menu doesn't
define padding styles.
=> Menu: Account for scrollbars in jQuery 3.2

ui/widgets/resizable.js
This prevents triggering CSP violation. If we do not want to use 'unsafe-inine'.
=> Fix: CSP violation (style unsafe-inline) in resizable widget

build/tasks/testswarm.js
This will make it easier to e.g. now exclude Edge Legacy when testing against
jQuery 4.x.
=> Build: Allow to specify browser sets to TestSwarm tasks

ui/widget.js
When using jQuery UI under use strict, options === true (default for ie tooltip show/hide) will throw 
Uncaught TypeError: Cannot create property 'complete' on boolean 'true'
on line
options.complete = callback;
=> Widget: fix handling of options === true under use strict in _show/_hide

tests/unit/core/core.html, tests/unit/core/selector.js, ui/focusable.js
"collapse" is similar to "hidden", with a slight difference in the case of `tr/tbody/td/colgroup` elements.
See https://www.w3.org/TR/CSS22/visufx.html#visibility
See https://www.w3.org/TR/CSS22/tables.html#dynamic-effects
See https://developer.mozilla.org/en-US/docs/Web/CSS/visibility#Table_example
"visibility: collapse" elements are always not focusable, though.
Commit d3025968f34 introduced this regression by testing with `!== "hidden"` instead of `=== "visible"`.
=> Focusable: Fix handling of `visibility: collapse`

.csslintrc, Gruntfile.js, package.json, tests/visual/menu/menu.html, tests/visual/selectmenu/selectmenu.html, tests/visual/slider/range_slider.html
=> Build: Update to the latest version of Grunt & many other packages

Gruntfile.js, package.json
Updated grunt-contrib-qunit version to 3.1.0 to provide puppeteer support as the older version was using phantomjs.
Updated Gruntfile with puppeteer configuration as well.
=> Build: Update grunt-contrib-qunit version from 1.0.1 to 4.0.0

tests/lib/qunit-assert-domequal.js
jQuery >=3.4.0 uses a special focus/blur handler pair needed to fix various
issues with checkboxes/radio buttons as well as being able to pass data in focus
triggers. This leaves extra focus & blur events if any of these events were ever
listened to at a particular element.
We've started skipping these handlers in the `domEqual` assertion in gh-1930 but
we missed a case where an event is triggered before any handler is attached -
jQuery >=3.4.0 attaches then an extra noop listener just to force the code path
to go through the setup code before the trigger happens. We now skip this extra
handler as well.
This fixes a test failure in "dialog: methods" destroy tests.
Ref jquery/jquery#4496
Ref gh-1930
=> Tests: Account for an extra noop focus/blur listener in jQuery >=3.4

ui/widgets/dialog.js
Focus re-triggering in jQuery 3.4/3.5 makes the original element
have its focus event propagated last, breaking the re-targeting.
Trigger focus in a delay in addition if needed to avoid the issue.
This fixes the "interaction between overlay and other dialogs" core dialog
test when tested against jQuery 3.4/3.5.
Ref jquery/jquery#4382
=> Dialog: Workaround broken focus re-triggering in jQuery 3.4/3.5

Gruntfile.js
Some bad pages are being detected as Catalan randomly which makes the build
fail. This is reproducible both locally & on Travis. This commit adds a new
regex to account for this error.
=> Build: Add a new htmllint error regex

tests/unit/draggable/options.js, tests/unit/sortable/options.js
Some of the APIs return fractional values in newer jQueries, making comparisons
sometimes not being 100% accurate. Allow some delta.
This is similar to what was already done in
98b539171b6e805fa79346a5e9896865e5213b9c but a few cases affecting IE and/or
Edge Legacy were missed.
=> Tests: Make some number comparisons less strict

Gruntfile.js
Some bad pages are being detected as Catalan randomly which makes the build
fail. This is reproducible both locally & on Travis. PR gh-1949 added a new
regex to account for this error but it didn't escape parens properly so it's
not matching the problematic error message.
Ref gh-1949
I tested the new regex against the error reported in https://travis-ci.com/github/jquery/jquery-ui/jobs/489208911 and it's matching.
=> Build: Fix the new htmllint error regex

tests/unit/dialog/core.js
In IE in jQuery 3.4+ a sequence:
```js
$( inputNode ).trigger( "focus" ).trigger( "blur" ).trigger( "focus" );
```
doesn't end up with a focused input. However, in this test we only want to check
that the last focused input receives the focus back when `_focusTabbable()` is
called which in reality doesn't happen so quickly so let's avoid the issue by
waiting a bit.
Ref jquery/jquery#4856
=> Tests: Fix the "dialog: core: focus tabbable" test in IE

tests/unit/tabs/core.js
In IE with jQuery 1.8 focusout may not happen immediately so some checks
need to be done later.
=> Tests: Accept delayed focusout in IE with jQuery 1.8

tests/unit/datepicker/options.js, ui/widgets/datepicker.js
Instead of using enormous HTML strings, various elements are now constructed
using jQuery APIs. This makes it more obvious user-provided data is used
correctly.
Fixes [#15284](https://bugs.jqueryui.com/ticket/15284)
=> Datepicker: Make sure text option are text, shorten HTML strings

ui/widgets/datepicker.js
Hi!
I am currently working on adapting application to work properlly with screen readers. 
My QA team pointed out that the datepicker.js component was not working correctly:
1. There wasn't information about currently selected day - fixed with `aria-current`
2. Selectpickers for choosing month/year wasn't labeled properly -  fixed with `aria-label`.
I fixed it locally in our project but I thought It will be nice to share my patch :)
=> Fix: Adapt datepicker.js for some a11y standards

tests/unit/datepicker/options.js, ui/widgets/datepicker.js
Add a new option named `onUpdateDatepicker` that allows a custom callback to be provided. If provided, the callback is called at the end of `$.datepicker._updateDatepicker`.
Currently, there is not a good way to manipulate the DOM for the datepicker calendar. Using a common example, if you want to add a custom button, you have to do it in a callback on both `beforeShow` and `onChangeMonthYear`.
If using an inline datepicker, you also have to add the custom button in `onSelect`. Furthermore, If you call `$('.my-date-picker').datepicker('refresh');`, the custom button goes away and there is no callback option or event to use for adding it back.
[Here is one of many stackoverflow.com posts on this problem](https://stackoverflow.com/questions/4598850/how-do-you-add-buttons-to-a-jquery-datepick …
=> Datepicker: Add option for onUpdateDatepicker callback

ui/widgets/datepicker.js
`selectDay()` use jQuery `html()` method on `td` cell to get the day value from DOM, but when user use translator or other extension, it return NaN value because the cell can contains non excepted content. We must use data- attribute to ensure that value cannot be altered.
- https://jqueryui.com/resources/demos/datepicker/localization.html
- https://translate.google.com/translate?hl=en&sl=fr&tl=pl&u=https%3A%2F%2Fjqueryui.com%2Fresources%2Fdemos%2Fdatepicker%2Flocalization.html
We got
```html
<td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2021">
<a class="ui-state-default" href="#">
<font style="vertical-align: inherit;"><font style="vertical-align: inherit;">22</font></font>
</a>
</td>
```
instead of 
```
<td class=" " data-handler="selectDay" …
```
=> Datepicker: Get selectedDay from data-date instead of element contents

build/release.js
jQuery UI 1.12.1 was released using an outdated (at the time of its release)
version of the download.jqueryui.com package; the latest ones wouldn't generate
relevant JS files.
This commit accounts for the changes so that the latest version can be used.
=> Build: Fix package generation

build/release.js
The older versions were not compatible with Node.js 10 & newer.
=> Build: Update dependencies passed to jquery-release

build/release-test.js, build/release.js
Past npm versions required the `--save` flag to save anything in `package.json`
when installing packages but newer ones do this by default. Pass `--no-save` to
restore the original behavior in the `release-test.js` script.
Also, update release dependencies for the 1.13 release.
=> Build: Don't save temporary npm dependencies to package.json, update release deps

ui/effect.js, ui/jquery-var-for-color.js
We need to create a local jQuery because jQuery Color relies on it and the
global may not exist with AMD and a custom build (trac-10199). This worked
in UI 1.12 but stopped in 1.13 as jQuery Color is now sourced as an AMD module
and the variable started being defined after jQuery Color code. To restore the
proper order, move the variable declaration to a separate small module loaded
before jQuery Color.
=> Effect: Define the jQuery variable before jQuery Color gets imported

Gruntfile.js, bower.json, external/jquery/LICENSE.txt, external/jquery/jquery.js, tests/lib/bootstrap.js
1. Update the default jQuery version from 1.12.4 to 3.6.0 in tests
2. Update jQuery used for demos to 3.6.0. jQuery 1.12.4 misses some Core APIs that jQuery UI depends on and that are not polyfilled in demos.
=> Docs:Tests: Update the default jQuery version from 1.12.4 to 3.6.0

themes/base/theme.css
A fix from 43254468de7d69b5422e667ba7ebbe864fc34a63 introduced a rule setting
`background-image` of a blank icon to none. However, the selector used for that
rule had lower specificity than another one: `.ui-button .ui-icon` which caused
dashes being shown over the icons.
We needed to increase the specificity of the `.ui-icon-blank` rule past the
above selector and past `.ui-button:hover .ui-icon`. We're doing it by repeating
the class name three times.
=> Theme: Fix blank icons having a background

themes/base/theme.css
This reverts three commits:
* https://github.com/jquery/jquery-ui/commit/1b0e947f46bc1261b15816f2dcbd239d83a86335 (https://github.com/jquery/jquery-ui/pull/1753)
* https://github.com/jquery/jquery-ui/commit/dde9b83df61d1d676e66cb2a2f7970dd44a05137
* https://github.com/jquery/jquery-ui/commit/265b8f5e533923b9b4c9cbd9f1dd7b7785423381
which caused styling issues when compared to UI 1.12.1.
This unfixes a few issues:
* https://github.com/jquery/download.jqueryui.com/issues/335
* https://bugs.jqueryui.com/ticket/15059
* https://forum.jquery.com/topic/checkboxradio-widget-checkbox-click-doesn-t-work-with-ui-lightness-theme-22-9-2016
However, old & known issues are better than new & unknown ones, especially with our current very limited resources.
=> Theme: Revert three theme commits that are causing styling issues

tests/unit/tooltip/core.js, ui/widget.js, ui/widgets/tooltip.js
The 1.13.0 release remove the try-catch that prevents spurious errors
Fixes: 1f2011e
Closes: jquerygh-1990
=> Tooltip: Don't crash on empty content

tests/unit/sortable/options.js, ui/widgets/sortable.js
PR gh-1793 removed setting `this.offset.parent` in the Draggable
`refreshPositions` method which broke position calculations when moving
a Draggable item into a connected Sortable. restore that assignment.
Ref gh-1793
Fixes gh-2001
=> Sortable: Fix positioning when moving a Draggable item into a Sortable

tests/unit/widget/core.js, ui/widget.js
Due to the fact the widget factory code is now in strict mode, the check for
being called without using the `new` keyword started breaking if you save the
widget constructor to a variable before calling it:
```js
var customWidget = $.custom.customWidget;
customWidget( {}, elem );
```
as then `this` is undefined and checking for `this._createWidget` crashes.
Account for that with an additional check.
Fixes gh-2015
=> Widget: Make contextless widget construction work

tests/unit/autocomplete/core.js, ui/widgets/autocomplete.js
Potential solution for https://github.com/jquery/jquery-ui/issues/2002. The bug is due to changes https://bugs.jqueryui.com/ticket/9357. This addresses the bug without undoing the fix reported there. Instead, it empties the live region instead of appending, and does so after a brief timeout so the live region isn't updated on every mousemove event or when quickly traversing through options
=> Autocomplete: Rewrite with a delay instead of appending the live region

.mailmap, AUTHORS.txt
Beyond the `AUTHORS.txt` changes, this accounts for a recent email change in
one of the commits.
=> Build: Add Felix to .mailmap, update AUTHORS.txt

tests/unit/autocomplete/core.js, tests/unit/selectmenu/core.js, tests/unit/tabs/core.js, ui/widget.js
jQuery UI 1.13.0 changed the logic attaching the `_untrackClassesElement`
listener in the `_classes` widget method; one of the side effects was calling
`this._on` for each node that needed the listener. That caused a severe
performance degradation for large comboboxes as each `_on` jQuery UI call
causes a jQuery `add` call that calls Sizzle's `uniqueSort` underneath.
Instead, collect the nodes that need the listener and then, outside of the loop,
create a jQuery object out of them and attach the listener once. That's still
slower than the jQuery 1.12 version but only slightly: 936 ms to 1.03s on a very
large list on a recent MacBook Pro, compared to ~30 seconds before this patch.
Fixes gh-2014
=> Widget: Optimize attachment of the _untrackClassesElement listener

build/release.js
Both unminified & minified versions of JS & CSS files are included, for all
themes, as well as images.
Fixes gh-2011
=> Build: Include all the files published to the CDN in npm/Bower packages

package.json
More details:
https://github.com/advisories/GHSA-rm36-94g8-835r
Fixes gh-2090
=> Build: Update Grunt to resolve CVE-2022-1537

tests/unit/checkboxradio/checkboxradio.html, tests/unit/checkboxradio/core.js, tests/unit/checkboxradio/methods.js, ui/widgets/checkboxradio.js
If you generate a Checkboxradio from a checkbox/radio with a label that
contains encoded HTML, e.g. `&lt;em&gt;test&lt;/em&gt;` this will work fine
at first. If, however a refresh is triggered on that instance (explicitly or
e.g. by turning it into a `Controlgroup`), the previously escaped HTML will
now be evaluated.
If the label was created based on some user input, this could lead to
unexpected code execution even though the initial output was escaped.
Fixes gh-2101
=> Checkboxradio: Don't re-evaluate text labels as HTML

ui/core.js
The `jquery-patch` reference was included with the `.js` extension which is
not allowed in AMD.
Fixes gh-2107
=> Core: Fix dependencies in ui/core.js

.github/workflows/test.yml
The following GitHub Actions workflow execution logs demonstrates that the GitHub Action token permissions are elevated:
https://github.com/jquery/jquery-ui/actions/runs/3218073141/jobs/5261823755#step:1:19
This PR fixes the issue.
In addition to this PR, if you have repo admin access, then you should consider setting the following permission so that new workflow files will default to read-only permissions
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository
Signed-off-by: Ashish Kurmi <akurmi@stepsecurity.io>
=> Build: Set minimum permission for GitHub Actions Token

demos/tabs/ajax.html
The wording was extremely jarring and could put potential users off. Made it better by fixing both grammar and punctuation.
=> Demos: Better wording for the purposefully broken tab

tests/unit/datepicker/options.js
I was working on an issue with Datepicker (#1971) and when running some tests found that the tests are run with periods other than "y", "m", "w", and "d", which are the only valid periods listed in the docs https://api.jqueryui.com/datepicker/.
I think this is a particular problem for the tests with "m" and "d", as "M" and "D" refer to something very different in the Datepicker dateFormat. The latter refer to day/month names while the former to dates/month numbers.
Happy Holidays!
=> Tests: Test only valid values for Datepicker defaultDate, min/maxDate

tests/unit/selectmenu/core.js, ui/widgets/selectmenu.js
Change a2b25ef6caae3e1a272214839b815a6387618124 made options with the `hidden` attribute skipped when rendering. However, that makes indexes misaligned with native options as hidden ones maintain their index values. Instead, don't skip hidden options but add the `hidden` attribute to the respective jQuery UI elements as well.
Fixes gh-2082
Ref a2b25ef6caae3e1a272214839b815a6387618124
=> Selectmenu: Fix selecting options following hidden ones

ui/widgets/dialog.js
The workaround triggering a second delayed focus to a tabbable element was applied in jQueries 3.4 & 3.5 to fix IE issues. It also needs to be applied in jQuery 3.6 which this commit adds.
This will no longer be needed in jQuery 3.7 and jQuery 3.x-git tests are already passing because of that.
=> Dialog: Fix IE tests about interactions with other dialogs

tests/unit/selectmenu/options.js
jQuery 3.0 & 3.1 used `getBoundingClientRect()` in its `width`/`height` calculations and that causes minor differences in fractional width computations. Allow a tiny delta in tests to fix those tests breaking in Firefox.
Ref jquery/jquery#3561
=> Tests: Fix selectmenu width tests in Firefox with jQuery 3.0 & 3.1

tests/unit/selectmenu/methods.js
jQuery PR jquery/jquery#5452 removed special handling of boolean attributes. Thankfully, this only broke a single jQuery UI test.
=> Tests: Fix tests with the Git Core build

bower.json, external/jquery/jquery.js
This was missed during the update from `3.7.0` to `3.7.1`.
=> Build: Update jquery-3.x to point to 3.7.1 instead of 3.7.0

tests/unit/dialog/methods.js
The test "#8958: dialog can be opened while opening" had special behavior in jQuery 1.8 and the patch from commit 7adb13ac7c30a7ba33f1db256952be77b9e7a310 broke those assumptions. Adjust the test so that it passes again.
=> Tests: Workaround a jQuery 1.8 issue with one dialog test

tests/unit/draggable/options.js
One of the changes is increasing `revertDuration` from 200 to 300. For some reason, when jQuery 3.1 is used in an iframe (which TestSwarm uses) the timings are lower than expected and `setTimeout` too slow and the check for animation happens too late.
=> Tests: Increase robustness of a draggable `revert` test

tests/unit/tabs/core.js
jQuery 3.6 has issues with focus handling in IE which breaks this test. The issues were fixed in jQuery 3.7, so we just accept them here.
=> Tests: Skip a problematic keyboard test in IE with jQuery 3.6

build/release.js
In particular, the `node-packager` update is required for the release process to work on newer Node.js versions.
=> Build: Update release dependencies

tests/lib/bootstrap.js, tests/unit/button/button.html, tests/unit/dialog/dialog.html, tests/unit/droppable/droppable.html, tests/unit/tabs/core.js, tests/unit/tooltip/tooltip.html, ui/effect.js, ui/effects/effect-transfer.js, ui/widgets/button.js, ui/widgets/dialog.js, ui/widgets/droppable.js, ui/widgets/resizable.js, ui/widgets/spinner.js, ui/widgets/tabs.js, ui/widgets/tooltip.js
Instead of checking whether `$.uiBackCompat` is explicitly set to `false` to skip applying backwards compatible patches, check whether `$.uiBackCompat` is explicitly set to `true` to apply those patches.
=> Core: Make back compat disabled by default

Gruntfile.js
`main` version of #2248.
Just like it has always worked in Core. This will help with size comparisons between 1.13 & 1.14.
After this PR:
```
$ grunt sizer
Running "requirejs:js" (requirejs) task
Running "uglify:main" (uglify) task
>> 1 file created 549 kB → 267 kB
Running "compare_size:all" (compare_size) task
raw     gz Sizes
549319 128757 dist/jquery-ui.js
266710  69612 dist/jquery-ui.min.js
Done.
```
Before, only the less interesting `raw` sizes were reported.
=> Build: Report compressed sizes in compare_size

.github/workflows/browserstack.yml, Gruntfile.js, package.json, tests/lib/bootstrap.js, tests/runner/browsers.js, tests/runner/run.js, tests/unit/datepicker/options.js, tests/unit/draggable/options.js, tests/unit/position/core.js
Removes code from the 1-13-stable branch that was used to build on jenkins and run tests on testswarm.
This is assuming we can still test on browserstack locally using the new test runner.
=> Tests: remove code supporting jenkins and testswarm

tests/unit/dialog/core.js, ui/widgets/dialog.js
PR for the issue outlined in https://github.com/jquery/jquery-ui/issues/2246 . Hope I've done everything in the correct manner. Was trying to follow http://contribute.jquery.org/commits-and-pull-requests/ as good as I was able to. 
In regards of the PR itself, broader considerations are outlined in the corresponding issue. But I've went with adding `aria-modal="true` only, since it is the least invasive and breaking option in regards of backward compatibility  to fix the problem. In short, elements in the background of a dialog modal are added to the AOM without the `aria-modal` attribute or the `dialog` element in place. And for the test i went with the same pattern that was applied if the `role` attribute is in place with a value of `dialog`. Therefore I've checked if the attribute …
=> Dialog: Add aria-modal support

demos/search.js
The `jqueryui.com` demos build process deAMDifies HTML files, replacing required JS files with direct script tags. On the other hand, when running demos locally from the jQuery UI repository, RequireJS is used.
This used to work fine until we got a new `search.js` file introduced in gh-2187. The deAMDifying process doesn't touch non-HTML files which made loading autocomplete demos crash on "require is not a function"
To resolve the issues without a major rearchitecture of the build process, the `search.js` file now detects AMD and uses `require`, falling back to relying on the `jQuery` global in the other case.
Ref gh-2187
Ref jquery/jqueryui.com#216
=> Demos: Make autocomplete demos work on jqueryui.com

tests/unit/datepicker/methods.js, ui/widgets/datepicker.js
Issue: https://github.com/jquery/jquery-ui/issues/2178 - date picker remains after being destroyed
We confirmed through git bisect that this commit, https://github.com/jquery/jquery-ui/commit/817ce38,  introduced a bug while fixing a memory leak with the date picker. This commit sets the current instance to null, https://github.com/jquery/jquery-ui/blob/5665215a8560832193735d9507a90d10e03b90c8/ui/widgets/datepicker.js#L440, to remove the date picker logic but fails to remove the UI widget. 
Our proposed fix is to hide the date picker when the destroy function using `$.datepicker._hideDatepicker();` so the user can no longer hover over a "ghost" date picker that can no longer be interacted with.
=> Datepicker: Hide the UI on destroy

tests/lib/common.js
The "common widget" tests, checking if a widget doesn't overwrite some core widget APIs wasn't running as it was incorrectly checking for `$.uiBackCompat === false` instead of `$.uiBackCompat !== true` after the default changed in gh-2250.
Fixing the check uncovered that the draggable & sortable modules do overwrite the `_trigger` method. Add an exception in the test for that; at this stage of the project we don't plan to change the implementation.
Ref gh-2250
=> Tests: Properly check `$.uiBackCompat` in common widget tests

tests/unit/resizable/core.js, tests/unit/resizable/options.js, ui/widgets/resizable.js
Fixes: #2277. 
This end up being a bug on "resizable", and as I have shown on the issue it's quite a weird behavior and it's not consistent across browsers.
The same bug applies to the resizable element and "alsoResize" elements, so I fixed it on both places.
Dialog widget uses "alsoResize" property to update dialog contents size (as seen on the initial issue). This PR fixes that as well.
I have added some tests for both "box-sizing: content-box" and "box-sizing: border-box".
=> Resizable: Fix content shrink on resize

demos/effect/default.html, tests/visual/effects/all.html, tests/visual/effects/effects.js
The transfer effect is deprecated and not present unless `$.uiBackCompat` is set to `true`. In previous UI versions, the default was including the backwards compat layer so these demos & tests worked; now they do not by default. Just remove them.
Fixes gh-2278
=> Effect: Remove demos & visual tests of the transfer effect

demos/effect/removeClass.html
These scripts are not served. jquery and jquery-ui are loaded below this in another way. I noticed it looking for CSP errors, but I think it may have been 404ing for 9 years.
=> Demos: remove 404 scripts from removeClass demo

.github/workflows/codeql-analysis.yml
This is backported from Core at:
https://github.com/jquery/jquery/blob/19716254877870ecd649272cadd00a0d0ff8be01/.github/workflows/codeql-analysis.yml
=> Build: Add a CodeQL non-mandatory check

tests/unit/jquery-patch/all.html, tests/unit/jquery-patch/jquery-patch.html
The pages were erroneously titled after "Form Reset Mixin".
=> Tests: Fix titles of `jquery-patch.js` tests

tests/unit/tabs/core.js, tests/unit/tabs/helper.js, ui/widgets/tabs.js
The previous private `_sanitizeSelector` API was not correctly escaping backslashes and is now removed. The native API should always be correct.
=> Tabs: Use `CSS.escape` for sanitizing selectors

tests/runner/createTestServer.js
The test server has a rule for `/tests/unit/*/*.html` paths that serves a proper local file. However, the parameters after `/unit/` were so far not escaped, leading to possibly reading a file from outside of the Git repository. Fix that by replacing non-alphanumeric characters that are also not `-` or `_`.
This should resolve one CodeQL alert.
=> Build: Fix an XSS in the test server HTML serving logic

tests/unit/widget/core.js, ui/widget.js
This is an edge case and it only affects code accepting untrusted input as a widget name, but it's still technically correct to filter these out.
=> Widget: Don't let widget name affect `$.ui` prototype & constructor

demos/effect/easing.html
I stumbled across this during CSP testing. https://jqueryui.com/easing/
- Skip `_default`, which is a string and breaks the loop early
- Adjust text styling so the easing names fit.
=> Demos: fix easing demos

package.json
The only other dependency that is upgradable is `grunt-eslint`, but it would require migrating to flat config.
=> Build: Upgrade jtr to 0.2.5

Gruntfile.js, bower.json, external/jquery-mousewheel/LICENSE.txt, external/jquery-mousewheel/jquery.mousewheel.js, tests/lib/helper.js, tests/lib/qunit.js, tests/lib/testIframe.js, tests/unit/spinner/core.js, tests/unit/spinner/mousewheel-wheel.html, ui/widgets/spinner.js
As of gh-2338, if one has loaded the jQuery MouseWheel plugin, the `mousewheel`
handler would fire the `wheel` one, but the `wheel` one would also run in
response to the native `wheel` event, resulting in double the distance handled
by the spinner. To prevent the issue, only fire the `wheel` handler from inside
the `mousewheel` on if the event was triggered by jQuery - jQuery will not care
that the underlying event is `wheel` and will only fire handlers for
`mousewheel`.
Also, add an iframe test using jQuery MouseWheel to not affect all the other
tests.
Ref gh-2338
=> Spinner: Prevent double mousewheel & wheel event handling

tests/unit/tabs/core.js, tests/unit/tabs/tabs.html, ui/widgets/tabs.js
When credentials are provided directly in the URL, e.g.:
https://username:password@www.example.com/
`location.href` strips out the auth part, but anchor links contain them, making
our `isLocal` computation broken. This fixes it by only looking at `origin`,
`pathname` & `search`.
Fixes gh-2213
Prior to jQuery UI 1.14.1, hashes in anchor hrefs were used directly. In
gh-2307, that was changed - by decoding - to support more complex IDs, e.g.
containing emojis which are automatically encoded in `anchor.hash`.
Unfortunately, that broke cases where the panel ID is decoded as well.
It turns out the spec mandates checking both. In the "scrolling to a fragment"
section of the HTML spec[^1]. That uses a concept of document's indicated
part[^2]. Slightly below there's an algorithm to compute the …
=> Tabs: Properly handle decoded/encoded anchor hashes & panel IDs, support URL-based credentials

.github/workflows/codeql-analysis.yml, .github/workflows/filestash.yml, .github/workflows/node.js.yml, .gitignore, package-lock.json
Changes:
1. Commit package-lock.json.
2. Use cache settings built into `actions/setup-node`, drop `actions/cache` - it is simpler to maintain that way and it fixes Windows-specific issues.
3. Switch from `npm install` to `npm ci` in CI.
4. Update `actions/checkout` from v4.2.2 to v5.0.0.
=> Build: Commit package-lock.json, improve caching in CI
